networks:
  webnet-sample-app:
    driver: bridge

services:
  sample-app-frontend:
    image: "sample-app-frontend:latest"
    restart: unless-stopped
    ports:
      - "8081:80"
    networks:
      - webnet-sample-app
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount NGINX configuration file
  sample-app-backend:
    image: "sample-app-backend:latest"
    restart: unless-stopped
    env_file:
      - .env.local
    networks:
      - webnet-sample-app